@startuml

skinparam componentStyle uml2

package "'Prontuario' Aggregate" <<Rectangle>> {
	class Prontuario <<(A,#fffab8) Aggregate Root>> {
		Long id
		Long pacienteId
		Long medicoResponsavelId
		String anamnese
		String diagnostico
		String prescricao
		Date dataAtendimento
		String tipoAtendimento
		String observacoes
	}
	class ProntuarioService <<(S,DarkSeaGreen) Service>> {
		void registrarAtendimento(Long pacienteId, Long medicoId, String diagnostico, String prescricao)
		List<Prontuario> listarPorPeriodo(Date inicio, Date fim)
	}
}


@enduml
