@startuml

skinparam componentStyle uml2

package "'Consulta' Aggregate" <<Rectangle>> {
	class Consulta <<(A,#fffab8) Aggregate Root>> {
		Long id
		Long pacienteId
		Long medicoId
		Date dataConsulta
		String horaConsulta
		String tipo
		String status
	}
	class GestaoConsultasService <<(S,DarkSeaGreen) Service>> {
		void agendarConsulta(Long pacienteId, Long medicoId, Date data, String hora, String tipo)
		void cancelarConsulta(Long consultaId)
		void concluirConsulta(Long consultaId)
	}
}


@enduml
